### ISSUE TITLE
you got the life_server?

### ISSUE THREAD

**Issue by shreddedgaming** [redeye83/Evo3Life#1]
thanks : D

**Comment by redeye83** [comment]
Its just the default one.
Whats your community details? would love to see what others do with my stuff :-)

**Comment by shreddedgaming** [comment]
So the life_server is the default Altis Life one?

I don't have it set up yet, I'm speaking to my server host tonight and asking them if they are able to possibly host this. 

Isn't there a file that creates the DB supposed to be in here, btw?

Also, you got a link to the modifications that these files suit? I have this link from EVO, https://mega.nz/#!LJRRySCb!ki6CIz6LNV2nFULEB-Nmbik1Cil0Jq1O0pRYA92b1nE just wondering if that's the right one.

Thanks!

**Comment by redeye83** [comment]
Thats the fake EVO, our addons are found on our website http://www.evo-life.net
When you get the @life_server files for default altis life it will include the files needed to setup your database.
